### PR TITLE
Block downloads of certain URLs altogether

### PR DESCRIPTION
**Pull request by fregante**
- For #112 

## In URL

Screenshot 9

## In file path

Screenshot 10

### CODE REVIEW

**Comment by FoxRefire** [comment]
This causes such false positives
https://github.com/trojan-gfw/trojan/tree/master/examples

**Review by FoxRefire — COMMENTED** [review]
This causes such false positives
[trojan-gfw/trojan@master/examples](https://github.com/trojan-gfw/trojan/tree/master/examples?rgh-link-date=2024-06-30T06%3A09%3A58Z)

**Comment by fregante** [comment]
Complain to Google 🙏 

It's either this or I have to retire the entire product since they just prefer blocking access to the entire thing.

**Comment by fregante** [comment]
I suppose I could block the specific URL that was reported but I'm not sure I wanna play whack-a-mole.

**Pull request merged**
