### PR TITLE
Handle token-related errors

### LINKED ISSUE #6: Handle API errors
404s are stuck on `Retrieving directory info…`

### PR DESCRIPTION
**Pull request by loilo**
Fixes #6 (again)

### CODE REVIEW

**Comment by fregante** [comment]
The API specifically returns `401 Unauthorized` in this case: 
```js
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```

Perhaps we could test for that and be clearer in the message:

```
The token provided is invalid or has expired.
```

**Comment by loilo** [comment]
Good point, will do.

**Comment by loilo** [comment]
Made the error messages a little more fine-grained, depending on HTTP status code.

Code | Error
-|-
401 | Token is invalid/has been revoked (to my knowledge, GitHub's Personal Access Tokens do not expire)
403 | Token rate limit has been exceeded (when the according header matches)
404 | Repository was not found
– | Fallback case if no other condition applied but response is not OK either.

**Comment by loilo** [comment]
Noooooo. I just discovered a typo. 😂

**Pull request merged**
